Handle Events with same topic hash properly
poanetwork/ex_abi pull request #115
Opened 2022-10-13 00:55 UTC by yashh

I added more context regarding events that have same topic but different indexed arguments [here](https://github.com/poanetwork/ex_abi/issues/114)

This change allows the library to handle Transfer event that has multiple variants of arguments properly.

`Transfer(address from, address to, uint256 tokenId)`
`Transfer(address indexed from, address indexed to, uint256 indexed  tokenId)`
`Transfer(address indexed from, address indexed to, uint256  tokenId)`

2022-10-15 10:25 UTC, ayrat555 requested changes
Looking good. a couple of comments

2022-10-15 10:25 UTC, ayrat555 commented on lib/abi/event.ex
> -           Util.find_selector_by_method_id(function_selectors, method_id) do
I think this function can be removed

2022-10-15 10:25 UTC, ayrat555 commented on lib/abi/util.ex
> +  def find_selector_by_event_id(function_selectors, method_id_target, topics_length) do
let's add a couple of tests for this function

2022-10-15 10:25 UTC, ayrat555 commented on lib/abi/event.ex
> +    topics_length = Enum.count(input_topics, fn x -> x != nil end)
`topics_length` is only used in the `find_selector_by_event_id`. Let's pass input_topics as the third parameter into `find_selector_by_event_id` and count there

2022-10-15 15:48 UTC, yashh commented on lib/abi/event.ex
> -           Util.find_selector_by_method_id(function_selectors, method_id) do
This function is still used when we call functions in the ABI

```elixir
iex> File.read!("priv/dog.abi.json")
      ...> |> Jason.decode!
      ...> |> ABI.parse_specification
      ...> |> ABI.find_and_decode("b85d0bd200000000000000000000000000000000000000000000000000000000000000010000000000000000000000000000000000000000000000000000000000000001" |> Base.decode16!(case: :lower))
      {%ABI.FunctionSelector{type: :function, function: "bark", input_names: ["at", "loudly"], method_id: <<184, 93, 11, 210>>, returns: [], types: [:address, :bool], state_mutability: :non_payable}, [<<0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1>>, true]}```

2022-10-15 16:15 UTC, yashh commented on lib/abi/event.ex
> +    topics_length = Enum.count(input_topics, fn x -> x != nil end)
done

2022-10-16 04:30 UTC, ayrat555 requested changes

2022-10-16 04:30 UTC, ayrat555 commented on lib/abi/util.ex
> +          topics_length = Enum.count(input_topics, fn x -> x != nil end)
you're calculating `topics_length` for every function selector. 

Let's move it outside of `Enum.find`

2022-10-16 04:58 UTC, yashh commented on lib/abi/util.ex
> +          topics_length = Enum.count(input_topics, fn x -> x != nil end)
done

2022-10-17 05:45 UTC, ayrat555 approved these changes

2022-10-17 05:45 UTC, ayrat555 commented
Thank you!

2022-10-17 05:45 UTC, merged